### ISSUE TITLE
webpack shimming

### ISSUE THREAD

**Issue by ricovitch** [jeef3/angular-swfobject#11]
Hello I'm trying to use this module in a webpack angular application, and struggle to load the swfobject-npm library correctly.
It seems webpack does not allow required libs to set window.xxx properties by default.
I tried various options described in the shimming documentation of webpack without success : https://webpack.github.io/docs/shimming-modules.html

Would you have any idea ?

**Comment by ricovitch** [comment]
I have a working version using these two weback require commands : 

```
require("expose?swfobject!exports?swfobject!swfobject-npm/swfobject/swfobject.js");
require("angular-swfobject");
```

**Comment by jeef3** [comment]
Hi, sorry, I have no idea. But glad to see you got it working!

**Comment by lmssrinivas** [comment]
Hi 

I am trying to load `swfobject` as global variable from `webpack` config because I have a custom library using `swfobject` library.

Any idea how to inject it.

I tried `imports-loader` and `expose`

**Comment by jeef3** [comment]
@lmssrinivas no idea, sorry. I would suggest Webpack docs on importing global modules?

**Comment by lmssrinivas** [comment]
Finally I fixed it by doing this in the module loader

```
{ test: /swfobject/, loader: 'exports-loader?swfobject' },
            { test: /SWFService/, loader: 'exports-loader?SWFService' },
``` 

Thanks @jeef3 for responding
