### ISSUE TITLE
template in swf-params

### ISSUE THREAD

**Issue by karneaud** [jeef3/angular-swfobject#6]
I'm not sure if this is a bug or I am doing it wrong but when I do

```
swf-params="{ wmode: '{{opacity}}' }"
```

the template doesn't seem to get updated with the value.

**Comment by jeef3** [comment]
Hi @karneaud. It's actually been a while since I last used Angular, but shouldn't that be:

```
swf-params="{ wmode: opacity }"
```

?

**Comment by karneaud** [comment]
@jeef3 

if i have 

```
<div ng-controller="cntrl">
<swf-object swf-width="{{width}}" >.....
</div>
```

why would it be

```
swf-params="{wmode: opacity}"
```

if opacity is a `$scope` variable?

**Comment by jeef3** [comment]
Did my suggestion not work?

`swf-params` expects an object, where `swf-width` expects a `number|string`. I can't find specific Angular documentation on it, but that's how objects are passed in to directives. `opacity` will map directly to your `$scope` variable and pass that through to the directive.

Have a quick look at this code example: http://jsfiddle.net/e1qg7smo/

**Comment by jeef3** [comment]
@karneaud did you end up getting this sorted? Closing for now.

**Comment by karneaud** [comment]
Nope! Wasn't worth the effort. Used another plugin try the angular media
